/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_wshackle_java4cplusplus_NativeRunnable */

#ifndef _Included_com_github_wshackle_java4cplusplus_NativeRunnable
#define _Included_com_github_wshackle_java4cplusplus_NativeRunnable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_wshackle_java4cplusplus_NativeRunnable
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_wshackle_java4cplusplus_NativeRunnable_run
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
