
}
// End of %NAMESPACE%

/**************************************************************
 * This C++ file was autogenerated by java4cpp. 
 * It is intended to be modified. It will not be overwritten if it already exists.
 *
 **************************************************************/
