/**************************************************************
 * This C++ file was autogenerated by java4cpp. 
 * It is intended to be modified. It will not be overwritten if it already exists.
 *
 **************************************************************/

#include "%HEADER%"
#include "%NATIVE_CLASS_HEADER%"

namespace %NAMESPACE% {

     void %CLASS_NAME%::initContext(%CLASS_NAME%Context *ctx, bool isref) {
         
    }

    void %CLASS_NAME%::deleteContext() {
        
    }

