/**************************************************************
 * This header file was autogenerated by java4cpp. 
 * It is intended to be modified. It will not be overwritten if it already exists.
 *
 **************************************************************/
#ifndef %NAMESPACE%_%CLASS_NAME%_H
#define %NAMESPACE%_%CLASS_NAME%_H

namespace %NAMESPACE% {

    class %CLASS_NAME%Context {
        // add any data to store per object
    };
}

#endif
// end of #ifndef %NAMESPACE%_%CLASS_NAME%_H
