/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * 
 */
package crcl.utils;


import crcl.base.CRCLCommandInstanceType;
import crcl.base.CRCLProgramType;
import crcl.base.InitCanonType;
import java.math.BigInteger;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 *
 * @author Will Shackleford {@literal <william.shackleford@nist.gov>}
 */
public class CRCLSocketIT {

    public CRCLSocketIT() {
    }

    @BeforeClass
    public static void setUpClass() {
    }

    @AfterClass
    public static void tearDownClass() {
    }

    @Before
    public void setUp() {
    }

    @After
    public void tearDown() {
    }

    /**
     * Test of stringToCommand method, of class CRCLSocket.
     */
    @Test
    public void testStringToCommand() throws Exception {
        System.out.println("stringToCommand");
        String str = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                + "<CRCLCommandInstance\n"
                + "  xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n"
                + "  xsi:noNamespaceSchemaLocation=\"../xmlSchemas/CRCLCommandInstance.xsd\">\n"
                + "  <CRCLCommand xsi:type=\"InitCanonType\">\n"
                + "    <CommandID>1</CommandID>\n"
                + "  </CRCLCommand>\n"
                + "</CRCLCommandInstance>";
        boolean validate = false;
        CRCLSocket instance = new CRCLSocket();
        CRCLCommandInstanceType result = instance.stringToCommand(str, validate);
        assertTrue(result.getCRCLCommand().getCommandID().compareTo(BigInteger.ONE) == 0);
        assertTrue(result.getCRCLCommand() instanceof InitCanonType);
//        fail("forced failure");
    }

    /**
     * Test of stringToProgram method, of class CRCLSocket.
     */
    @Test
    public void testStringToProgram() throws Exception {
        System.out.println("stringToProgram");
        String str = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                + "<CRCLProgram\n"
                + "  xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n"
                + "  xsi:noNamespaceSchemaLocation=\"../xmlSchemas/CRCLProgramInstance.xsd\">\n"
                + "  <InitCanon>\n"
                + "    <CommandID>1</CommandID>\n"
                + "  </InitCanon>\n"
                + "  <MiddleCommand xsi:type=\"SetLengthUnitsType\">\n"
                + "    <CommandID>2</CommandID>\n"
                + "    <UnitName>meter</UnitName>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"SetTransSpeedType\">\n"
                + "    <CommandID>3</CommandID>\n"
                + "    <TransSpeed xsi:type=\"TransSpeedAbsoluteType\">\n"
                + "      <Setting>1.0</Setting>\n"
                + "    </TransSpeed>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"SetTransAccelType\">\n"
                + "    <CommandID>4</CommandID>\n"
                + "    <TransAccel xsi:type=\"TransAccelRelativeType\">\n"
                + "      <Fraction>0.80</Fraction>\n"
                + "    </TransAccel>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"SetEndPoseToleranceType\">\n"
                + "    <CommandID>5</CommandID>\n"
                + "    <Tolerance>\n"
                + "      <XPointTolerance>0.002</XPointTolerance>\n"
                + "      <YPointTolerance>0.002</YPointTolerance>\n"
                + "      <ZPointTolerance>0.002</ZPointTolerance>\n"
                + "    </Tolerance>\n"
                + "   </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"SetIntermediatePoseToleranceType\">\n"
                + "    <CommandID>6</CommandID>\n"
                + "    <Tolerance>\n"
                + "      <XPointTolerance>0.01</XPointTolerance>\n"
                + "      <YPointTolerance>0.01</YPointTolerance>\n"
                + "      <ZPointTolerance>0.01</ZPointTolerance>\n"
                + "    </Tolerance>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"SetEndEffectorType\">\n"
                + "    <CommandID>7</CommandID>\n"
                + "    <Setting>0</Setting>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"MoveThroughToType\">\n"
                + "    <CommandID>8</CommandID>\n"
                + "    <MoveStraight>false</MoveStraight>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>1.5</X> <Y>1</Y> <Z>1</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>1.5</X> <Y>1</Y> <Z>0.0001</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <NumPositions>2</NumPositions>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"SetEndEffectorType\">\n"
                + "    <CommandID>9</CommandID>\n"
                + "    <Setting>1</Setting>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"MoveThroughToType\">\n"
                + "    <CommandID>10</CommandID>\n"
                + "    <MoveStraight>false</MoveStraight>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>1.5</X> <Y>1</Y> <Z>1</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>4</X> <Y>1</Y> <Z>1</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>4</X> <Y>1</Y> <Z>0.5001</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <NumPositions>3</NumPositions>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"SetEndEffectorType\">\n"
                + "    <CommandID>11</CommandID>\n"
                + "    <Setting>0</Setting>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"MoveThroughToType\">\n"
                + "    <CommandID>12</CommandID>\n"
                + "    <MoveStraight>false</MoveStraight>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>4</X> <Y>1</Y> <Z>1</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>8.25</X> <Y>1</Y> <Z>1</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>8.25</X> <Y>1</Y> <Z>0.4</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <NumPositions>3</NumPositions>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"OpenToolChangerType\">\n"
                + "    <CommandID>13</CommandID>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"MoveThroughToType\">\n"
                + "    <CommandID>14</CommandID>\n"
                + "    <MoveStraight>false</MoveStraight>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>8.25</X> <Y>1</Y> <Z>1</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>8.75</X> <Y>1</Y> <Z>1</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>8.75</X> <Y>1</Y> <Z>0.5</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <NumPositions>3</NumPositions>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"CloseToolChangerType\">\n"
                + "    <CommandID>15</CommandID>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"MoveThroughToType\">\n"
                + "    <CommandID>16</CommandID>\n"
                + "    <MoveStraight>false</MoveStraight>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>8.75</X> <Y>1</Y> <Z>1</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>5.659</X> <Y>1.1</Y> <Z>1.8</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>5.659</X> <Y>1.1</Y> <Z>0.1501</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <NumPositions>3</NumPositions>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"SetEndEffectorType\">\n"
                + "    <CommandID>17</CommandID>\n"
                + "    <Setting>1</Setting>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"MoveThroughToType\">\n"
                + "    <CommandID>18</CommandID>\n"
                + "    <MoveStraight>false</MoveStraight>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>5.659</X> <Y>1.1</Y> <Z>0.5</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>3.86</X> <Y>1.07</Y> <Z>1</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>3.86</X> <Y>1.07</Y> <Z>0.6501</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <NumPositions>3</NumPositions>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"SetEndEffectorType\">\n"
                + "    <CommandID>19</CommandID>\n"
                + "    <Setting>0</Setting>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"MoveThroughToType\">\n"
                + "    <CommandID>20</CommandID>\n"
                + "    <MoveStraight>false</MoveStraight>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>3.86</X> <Y>1.07</Y> <Z>1</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>5.659</X> <Y>0.9</Y> <Z>0.5</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>5.659</X> <Y>0.9</Y> <Z>0.1501</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <NumPositions>3</NumPositions>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"SetEndEffectorType\">\n"
                + "    <CommandID>21</CommandID>\n"
                + "    <Setting>1</Setting>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"MoveThroughToType\">\n"
                + "    <CommandID>22</CommandID>\n"
                + "    <MoveStraight>false</MoveStraight>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>5.659</X> <Y>0.9</Y> <Z>0.5</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>3.86</X> <Y>0.93</Y> <Z>1</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>3.86</X> <Y>0.93</Y> <Z>0.6501</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <NumPositions>3</NumPositions>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"SetEndEffectorType\">\n"
                + "    <CommandID>23</CommandID>\n"
                + "    <Setting>0</Setting>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"MoveThroughToType\">\n"
                + "    <CommandID>24</CommandID>\n"
                + "    <MoveStraight>false</MoveStraight>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>3.86</X> <Y>0.93</Y> <Z>1</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>6.42</X> <Y>1</Y> <Z>0.5</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>6.42</X> <Y>1</Y> <Z>0.1501</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <NumPositions>3</NumPositions>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"SetEndEffectorType\">\n"
                + "    <CommandID>25</CommandID>\n"
                + "    <Setting>1</Setting>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"MoveThroughToType\">\n"
                + "    <CommandID>26</CommandID>\n"
                + "    <MoveStraight>false</MoveStraight>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>6.42</X> <Y>1</Y> <Z>0.5</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>4.14</X> <Y>0.93</Y> <Z>1</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>4.14</X> <Y>0.93</Y> <Z>0.6501</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <NumPositions>3</NumPositions>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"SetEndEffectorType\">\n"
                + "    <CommandID>27</CommandID>\n"
                + "    <Setting>0</Setting>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"MoveThroughToType\">\n"
                + "    <CommandID>28</CommandID>\n"
                + "    <MoveStraight>false</MoveStraight>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>4.14</X> <Y>0.93</Y> <Z>1</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>7.61</X> <Y>1.02</Y> <Z>0.5</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>7.61</X> <Y>1.02</Y> <Z>0.1501</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <NumPositions>3</NumPositions>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"SetEndEffectorType\">\n"
                + "    <CommandID>29</CommandID>\n"
                + "    <Setting>1</Setting>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"MoveThroughToType\">\n"
                + "    <CommandID>30</CommandID>\n"
                + "    <MoveStraight>false</MoveStraight>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>7.61</X> <Y>1.02</Y> <Z>0.5</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>4.14</X> <Y>1.07</Y> <Z>1</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>4.14</X> <Y>1.07</Y> <Z>0.6501</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <NumPositions>3</NumPositions>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"SetEndEffectorType\">\n"
                + "    <CommandID>31</CommandID>\n"
                + "    <Setting>0</Setting>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"MoveThroughToType\">\n"
                + "    <CommandID>32</CommandID>\n"
                + "    <MoveStraight>false</MoveStraight>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>4.14</X> <Y>1.07</Y> <Z>1</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>8.75</X> <Y>1</Y> <Z>1</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>8.75</X> <Y>1</Y> <Z>0.475</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <NumPositions>3</NumPositions>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"OpenToolChangerType\">\n"
                + "    <CommandID>33</CommandID>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"MoveThroughToType\">\n"
                + "    <CommandID>34</CommandID>\n"
                + "    <MoveStraight>false</MoveStraight>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>8.75</X> <Y>1</Y> <Z>1</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>8.25</X> <Y>1</Y> <Z>1</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>8.25</X> <Y>1</Y> <Z>0.5</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <NumPositions>3</NumPositions>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"CloseToolChangerType\">\n"
                + "    <CommandID>35</CommandID>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"MoveThroughToType\">\n"
                + "    <CommandID>36</CommandID>\n"
                + "    <MoveStraight>false</MoveStraight>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>8.25</X> <Y>1</Y> <Z>1</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>4</X> <Y>1</Y> <Z>1</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>4</X> <Y>1</Y> <Z>0.5001</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <NumPositions>3</NumPositions>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"SetEndEffectorType\">\n"
                + "    <CommandID>37</CommandID>\n"
                + "    <Setting>1</Setting>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"MoveThroughToType\">\n"
                + "    <CommandID>38</CommandID>\n"
                + "    <MoveStraight>false</MoveStraight>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>4</X> <Y>1</Y> <Z>1</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>2.5</X> <Y>1</Y> <Z>1</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>2.5</X> <Y>1</Y> <Z>0.0001</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <NumPositions>3</NumPositions>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"SetEndEffectorType\">\n"
                + "    <CommandID>39</CommandID>\n"
                + "    <Setting>0</Setting>\n"
                + "  </MiddleCommand>\n"
                + "  <MiddleCommand xsi:type=\"MoveThroughToType\">\n"
                + "    <CommandID>40</CommandID>\n"
                + "    <MoveStraight>false</MoveStraight>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>2.5</X> <Y>1</Y> <Z>1</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <Waypoint>\n"
                + "      <Point>\n"
                + "        <X>0.5</X> <Y>0</Y> <Z>2</Z>\n"
                + "      </Point>\n"
                + "      <XAxis>\n"
                + "        <I>1</I> <J>0</J> <K>0</K>\n"
                + "      </XAxis>\n"
                + "      <ZAxis>\n"
                + "        <I>0</I> <J>0</J> <K>-1</K>\n"
                + "      </ZAxis>\n"
                + "    </Waypoint>\n"
                + "    <NumPositions>2</NumPositions>\n"
                + "  </MiddleCommand>\n"
                + "  <EndCanon>\n"
                + "    <CommandID>41</CommandID>\n"
                + "  </EndCanon>\n"
                + "</CRCLProgram>";
        boolean validate = false;
        CRCLSocket instance = new CRCLSocket();
        CRCLProgramType result = instance.stringToProgram(str, validate);
        assertTrue(result.getInitCanon().getCommandID().compareTo(BigInteger.ONE) == 0);
        assertEquals(result.getMiddleCommand().size(), 39);
        assertTrue(result.getEndCanon().getCommandID().compareTo(BigInteger.valueOf(41)) == 0);

    }

    /**
     * Test of statusToString method, of class CRCLSocket.
     */
//    @Test
//    public void testStatusToString() throws Exception {
//        System.out.println("statusToPrettyString");
//        boolean validate = false;
//        CRCLSocket instance = new CRCLSocket();
//        CRCLStatusType status = instance.stringToStatus("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
//                + "<CRCLStatus\n"
//                + "  xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n"
//                + "  xsi:noNamespaceSchemaLocation=\"../xmlSchemas/CRCLStatus.xsd\">\n"
//                + "  <CommandStatus>\n"
//                + "    <CommandID>5</CommandID>\n"
//                + "    <StatusID>1</StatusID>\n"
//                + "    <CommandState>Working</CommandState>\n"
//                + "  </CommandStatus>\n"
//                + "  <JointStatuses>\n"
//                + "    <JointStatus>\n"
//                + "      <JointNumber>1</JointNumber>\n"
//                + "      <JointPosition>8.000000</JointPosition>\n"
//                + "    </JointStatus>\n"
//                + "    <JointStatus>\n"
//                + "      <JointNumber>2</JointNumber>\n"
//                + "      <JointPosition>53.000000</JointPosition>\n"
//                + "    </JointStatus>\n"
//                + "    <JointStatus>\n"
//                + "      <JointNumber>3</JointNumber>\n"
//                + "      <JointPosition>-98.000000</JointPosition>\n"
//                + "    </JointStatus>\n"
//                + "    <JointStatus>\n"
//                + "      <JointNumber>4</JointNumber>\n"
//                + "      <JointPosition>82.000000</JointPosition>\n"
//                + "    </JointStatus>\n"
//                + "    <JointStatus>\n"
//                + "      <JointNumber>5</JointNumber>\n"
//                + "      <JointPosition>-8.000000</JointPosition>\n"
//                + "    </JointStatus>\n"
//                + "    <JointStatus>\n"
//                + "      <JointNumber>6</JointNumber>\n"
//                + "      <JointPosition>0.000000</JointPosition>\n"
//                + "    </JointStatus>\n"
//                + "  </JointStatuses>\n"
//                + "  <Pose>\n"
//                + "    <Timestamp>2015-04-02T09:55:44.455-04:00</Timestamp>\n"
//                + "    <Point>\n"
//                + "      <X>102.519869</X>\n"
//                + "      <Y>12.724614</Y>\n"
//                + "      <Z>36.635392</Z>\n"
//                + "    </Point>\n"
//                + "    <XAxis>\n"
//                + "      <I>0.798636</I>\n"
//                + "      <J>0.000000</J>\n"
//                + "      <K>0.601815</K>\n"
//                + "    </XAxis>\n"
//                + "    <ZAxis>\n"
//                + "      <I>-0.601815</I>\n"
//                + "      <J>0.000000</J>\n"
//                + "      <K>0.798636</K>\n"
//                + "    </ZAxis>\n"
//                + "  </Pose>\n"
//                + "</CRCLStatus> ", validate);
//        String expResult = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
//                + "<CRCLStatus\n"
//                + "  xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n"
//                + "  xsi:noNamespaceSchemaLocation=\"../xmlSchemas/CRCLStatus.xsd\"><CommandStatus><CommandID>5</CommandID><StatusID>1</StatusID></CommandStatus><JointStatuses><JointStatus><JointNumber>1</JointNumber><JointPosition>8.000000</JointPosition></JointStatus><JointStatus><JointNumber>2</JointNumber><JointPosition>53.000000</JointPosition></JointStatus><JointStatus><JointNumber>3</JointNumber><JointPosition>-98.000000</JointPosition></JointStatus><JointStatus><JointNumber>4</JointNumber><JointPosition>82.000000</JointPosition></JointStatus><JointStatus><JointNumber>5</JointNumber><JointPosition>-8.000000</JointPosition></JointStatus><JointStatus><JointNumber>6</JointNumber><JointPosition>0.000000</JointPosition></JointStatus></JointStatuses><Pose><Timestamp>2015-04-02T09:55:44.455-04:00</Timestamp><Point><X>102.519869</X><Y>12.724614</Y><Z>36.635392</Z></Point><XAxis><I>0.798636</I><J>0.000000</J><K>0.601815</K></XAxis><ZAxis><I>-0.601815</I><J>0.000000</J><K>0.798636</K></ZAxis></Pose></CRCLStatus>";
//        String result = instance.statusToString(status, validate);
//        System.out.println("result = " + result);
//
//        for (int i = 0; i < Math.min(result.length(), expResult.length()); i++) {
//            if (expResult.charAt(i) != result.charAt(i)) {
//                System.out.println("expResult.substring(" + i + ")=" + expResult.substring(i));
//                System.out.println("result.substring(" + i + ")=" + result.substring(i));
//                break;
//            }
//        }
////        System.out.println("resultPart = " + resultPart);
////        System.out.println("expResultPart = " + expResultPart);
//        assertEquals(expResult, result);
//    }

}
