#ifndef crclj_fwd_h
#define crclj_fwd_h


namespace crclj {
    
    namespace java {
            namespace lang {
                class Object;
            } // end namespace lang;
    }// end namespace java 
    
   

    
    namespace crcl{
        namespace base{
            class DataThingType;
             class CRCLCommandType;
              class MiddleCommandType;
               class MessageType;
                class JointDetailsType;
               } // end namespace base
              } // end namespace crcl

                 namespace java{
                     namespace lang{
                         class Enum;
                        } // end namespace lang
                       } // end namespace java

                          namespace crcl{
                              namespace base{
                                  class LengthUnitEnumType;
                                   class SetRotAccelType;
                                    class SetAngleUnitsType;
                                     class CommandStatusType;
                                      class PoseStatusType;
                                       class TransSpeedType;
                                        class TransSpeedRelativeType;
                                         class SetForceUnitsType;
                                          class JointStatusType;
                                         } // end namespace base

                                           namespace utils{
                                               class SimServerOuterStub;
                                                class SimServerOuter;
                                               } // end namespace utils

                                                 namespace base{
                                                     class PoseToleranceType;
                                                      class VectorType;
                                                       class SetRotSpeedType;
                                                        class ConfigureStatusReportType;
                                                         class SetTorqueUnitsType;
                                                        } // end namespace base

                                                          namespace utils{
                                                              class Predicate;
                                                             } // end namespace utils

                                                               namespace base{
                                                                   class RotSpeedType;
                                                                    class WrenchType;
                                                                     class ConfigureJointReportsType;
                                                                      class RotSpeedRelativeType;
                                                                       class RunProgramType;
                                                                        class RotAccelType;
                                                                         class RotAccelRelativeType;
                                                                          class MoveThroughToType;
                                                                           class GetStatusType;
                                                                            class TwistType;
                                                                             class MoveScrewType;
                                                                              class RotAccelAbsoluteType;
                                                                               class SetMotionCoordinationType;
                                                                                class ActuateJointType;
                                                                                 class RotSpeedAbsoluteType;
                                                                                } // end namespace base

                                                                                  namespace utils{
                                                                                      class CRCLServerSocketEventListener;
                                                                                       class PerfTest;
                                                                                        class SimulatedKinematicsPlausible;
                                                                                       } // end namespace utils
                                                                                      } // end namespace crcl

                                                                                         namespace java{
                                                                                             namespace lang{
                                                                                                 class Throwable;
                                                                                                  class Exception;
                                                                                                 } // end namespace lang
                                                                                                } // end namespace java

                                                                                                   namespace crcl{
                                                                                                       namespace utils{
                                                                                                           class CRCLException;
                                                                                                          } // end namespace utils
                                                                                                         } // end namespace crcl

                                                                                                            namespace rcs{
                                                                                                                namespace posemath{
                                                                                                                    class PmPose;
                                                                                                                   } // end namespace posemath
                                                                                                                  } // end namespace rcs

                                                                                                                     namespace crcl{
                                                                                                                         namespace utils{
                                                                                                                             class AnnotatedPose;
                                                                                                                              class CRCLSocket;
                                                                                                                             } // end namespace utils

                                                                                                                               namespace base{
                                                                                                                                   class GripperStatusType;
                                                                                                                                    class CRCLCommandInstanceType;
                                                                                                                                     class ThreeFingerGripperStatusType;
                                                                                                                                    } // end namespace base

                                                                                                                                      namespace utils{
                                                                                                                                          class PoseToleranceChecker;
                                                                                                                                           class SimRobotEnum;
                                                                                                                                            class XpathUtils;
                                                                                                                                             class SimulatedKinematicsSimple;
                                                                                                                                            } // end namespace utils

                                                                                                                                              namespace base{
                                                                                                                                                  class CRCLProgramType;
                                                                                                                                                   class TransAccelType;
                                                                                                                                                    class TorqueUnitEnumType;
                                                                                                                                                     class AngleUnitEnumType;
                                                                                                                                                      class SetIntermediatePoseToleranceType;
                                                                                                                                                       class TransAccelAbsoluteType;
                                                                                                                                                        class StopMotionType;
                                                                                                                                                         class CloseToolChangerType;
                                                                                                                                                          class VacuumGripperStatusType;
                                                                                                                                                           class SetEndEffectorParametersType;
                                                                                                                                                            class EndCanonType;
                                                                                                                                                             class StopConditionEnumType;
                                                                                                                                                            } // end namespace base

                                                                                                                                                              namespace utils{
                                                                                                                                                                  class CRCLPosemath;
                                                                                                                                                                   class Function;
                                                                                                                                                                  } // end namespace utils

                                                                                                                                                                    namespace base{
                                                                                                                                                                        class ActuateJointsType;
                                                                                                                                                                         class PoseType;
                                                                                                                                                                          class JointSpeedAccelType;
                                                                                                                                                                           class TransSpeedAbsoluteType;
                                                                                                                                                                            class ForceUnitEnumType;
                                                                                                                                                                             class CRCLStatusType;
                                                                                                                                                                              class SetRobotParametersType;
                                                                                                                                                                               class MoveToType;
                                                                                                                                                                              } // end namespace base

                                                                                                                                                                                namespace utils{
                                                                                                                                                                                    class CRCLServerSocketEvent;
                                                                                                                                                                                     class CRCLServerSocket;
                                                                                                                                                                                      class PendantClientOuterStub;
                                                                                                                                                                                       class ProgramPlotter;
                                                                                                                                                                                      } // end namespace utils

                                                                                                                                                                                        namespace base{
                                                                                                                                                                                            class InitCanonType;
                                                                                                                                                                                             class SetEndEffectorType;
                                                                                                                                                                                              class JointLimitType;
                                                                                                                                                                                               class ConfigureJointReportType;
                                                                                                                                                                                                class SetEndPoseToleranceType;
                                                                                                                                                                                                 class ParameterSettingType;
                                                                                                                                                                                                  class SetTransSpeedType;
                                                                                                                                                                                                   class JointStatusesType;
                                                                                                                                                                                                    class ParallelGripperStatusType;
                                                                                                                                                                                                     class ObjectFactory;
                                                                                                                                                                                                      class PoseAndSetType;
                                                                                                                                                                                                       class SettingsStatusType;
                                                                                                                                                                                                        class TransAccelRelativeType;
                                                                                                                                                                                                         class DwellType;
                                                                                                                                                                                                          class SetLengthUnitsType;
                                                                                                                                                                                                           class OpenToolChangerType;
                                                                                                                                                                                                            class SetTransAccelType;
                                                                                                                                                                                                             class JointForceTorqueType;
                                                                                                                                                                                                              class PointType;
                                                                                                                                                                                                               class CommandStateEnumType;
                                                                                                                                                                                                              } // end namespace base

                                                                                                                                                                                                                namespace utils{
                                                                                                                                                                                                                    class PendantClientOuter;
                                                                                                                                                                                                                   } // end namespace utils
                                                                                                                                                                                                                  } // end namespace crcl

                                                                                                                                                                                                                     namespace java{
                                                                                                                                                                                                                         namespace lang{
                                                                                                                                                                                                                             class Number;
                                                                                                                                                                                                                            } // end namespace lang

                                                                                                                                                                                                                              namespace math{
                                                                                                                                                                                                                                  class BigInteger;
                                                                                                                                                                                                                                   class BigDecimal;
                                                                                                                                                                                                                                  } // end namespace math

                                                                                                                                                                                                                                    namespace util{
                                                                                                                                                                                                                                        class List;
                                                                                                                                                                                                                                       } // end namespace util
                                                                                                                                                                                                                                      } // end namespace java

                                                                                                                                                                                                                                         namespace crcl{
                                                                                                                                                                                                                                             namespace utils{
                                                                                                                                                                                                                                                 class PerfTestMinMaxAvg;
                                                                                                                                                                                                                                                } // end namespace utils
                                                                                                                                                                                                                                               } // end namespace crcl

                                                                                                                                                                                                                                                  namespace java{
                                                                                                                                                                                                                                                      namespace awt{
                                                                                                                                                                                                                                                          namespace geom{
                                                                                                                                                                                                                                                              class Point2D;
                                                                                                                                                                                                                                                              class Point2DDouble;
                                                                                                                                                                                                                                                             } // end namespace geom
                                                                                                                                                                                                                                                            } // end namespace awt
                                                                                                                                                                                                                                                           } // end namespace java

                                                                                                                                                                                                                                                              namespace rcs{
                                                                                                                                                                                                                                                                  namespace posemath{
                                                                                                                                                                                                                                                                      class PmCartesian;
                                                                                                                                                                                                                                                                       class PmQuaternion;
                                                                                                                                                                                                                                                                      } // end namespace posemath
                                                                                                                                                                                                                                                                     } // end namespace rcs

                                                                                                                                                                                                                                                                        namespace crcl{
                                                                                                                                                                                                                                                                            namespace utils{
                                                                                                                                                                                                                                                                                class CRCLSocketUnaryOperator;
                                                                                                                                                                                                                                                                               } // end namespace utils
                                                                                                                                                                                                                                                                              } // end namespace crcl

                                                                                                                                                                                                                                                                                 namespace javax{
                                                                                                                                                                                                                                                                                     namespace xml{
                                                                                                                                                                                                                                                                                         namespace validation{
                                                                                                                                                                                                                                                                                             class Schema;
                                                                                                                                                                                                                                                                                            } // end namespace validation
                                                                                                                                                                                                                                                                                           } // end namespace xml
                                                                                                                                                                                                                                                                                          } // end namespace javax

                                                                                                                                                                                                                                                                                             namespace java{
                                                                                                                                                                                                                                                                                                 namespace io{
                                                                                                                                                                                                                                                                                                     class File;
                                                                                                                                                                                                                                                                                                    } // end namespace io

                                                                                                                                                                                                                                                                                                      namespace net{
                                                                                                                                                                                                                                                                                                          class InetAddress;
                                                                                                                                                                                                                                                                                                           class Socket;
                                                                                                                                                                                                                                                                                                          } // end namespace net
                                                                                                                                                                                                                                                                                                         } // end namespace java

                                                                                                                                                                                                                                                                                                            namespace crcl{
                                                                                                                                                                                                                                                                                                                namespace utils{
                                                                                                                                                                                                                                                                                                                    class CRCLSocketCRCLSocketConsumer;
                                                                                                                                                                                                                                                                                                                   } // end namespace utils
                                                                                                                                                                                                                                                                                                                  } // end namespace crcl

                                                                                                                                                                                                                                                                                                                     namespace java{
                                                                                                                                                                                                                                                                                                                         namespace nio{
                                                                                                                                                                                                                                                                                                                             namespace file{
                                                                                                                                                                                                                                                                                                                                 class Path;
                                                                                                                                                                                                                                                                                                                                } // end namespace file
                                                                                                                                                                                                                                                                                                                               } // end namespace nio

                                                                                                                                                                                                                                                                                                                                 namespace util{
                                                                                                                                                                                                                                                                                                                                     class Map;
                                                                                                                                                                                                                                                                                                                                    } // end namespace util

                                                                                                                                                                                                                                                                                                                                      namespace nio{
                                                                                                                                                                                                                                                                                                                                          namespace channels{
                                                                                                                                                                                                                                                                                                                                              namespace spi{
                                                                                                                                                                                                                                                                                                                                                  class AbstractInterruptibleChannel;
                                                                                                                                                                                                                                                                                                                                                 } // end namespace spi

                                                                                                                                                                                                                                                                                                                                                 class SelectableChannel;
                                                                                                                                                                                                                                                                                                                                                 namespace spi{
                                                                                                                                                                                                                                                                                                                                                     class AbstractSelectableChannel;
                                                                                                                                                                                                                                                                                                                                                    } // end namespace spi

                                                                                                                                                                                                                                                                                                                                                    class SocketChannel;
                                                                                                                                                                                                                                                                                                                                                   } // end namespace channels
                                                                                                                                                                                                                                                                                                                                                  } // end namespace nio

                                                                                                                                                                                                                                                                                                                                                    namespace io{
                                                                                                                                                                                                                                                                                                                                                        class InputStream;
                                                                                                                                                                                                                                                                                                                                                       } // end namespace io
                                                                                                                                                                                                                                                                                                                                                      } // end namespace java

                                                                                                                                                                                                                                                                                                                                                         namespace javax{
                                                                                                                                                                                                                                                                                                                                                             namespace xml{
                                                                                                                                                                                                                                                                                                                                                                 namespace transform{
                                                                                                                                                                                                                                                                                                                                                                     namespace sax{
                                                                                                                                                                                                                                                                                                                                                                         class SAXSource;
                                                                                                                                                                                                                                                                                                                                                                        } // end namespace sax
                                                                                                                                                                                                                                                                                                                                                                       } // end namespace transform
                                                                                                                                                                                                                                                                                                                                                                      } // end namespace xml
                                                                                                                                                                                                                                                                                                                                                                     } // end namespace javax

                                                                                                                                                                                                                                                                                                                                                                        namespace java{
                                                                                                                                                                                                                                                                                                                                                                            namespace lang{
                                                                                                                                                                                                                                                                                                                                                                                class Boolean;
                                                                                                                                                                                                                                                                                                                                                                               } // end namespace lang
                                                                                                                                                                                                                                                                                                                                                                              } // end namespace java

                                                                                                                                                                                                                                                                                                                                                                                 namespace org{
                                                                                                                                                                                                                                                                                                                                                                                     namespace w3c{
                                                                                                                                                                                                                                                                                                                                                                                         namespace dom{
                                                                                                                                                                                                                                                                                                                                                                                             class Node;
                                                                                                                                                                                                                                                                                                                                                                                             class NodeList;
                                                                                                                                                                                                                                                                                                                                                                                            } // end namespace dom
                                                                                                                                                                                                                                                                                                                                                                                           } // end namespace w3c
                                                                                                                                                                                                                                                                                                                                                                                          } // end namespace org

                                                                                                                                                                                                                                                                                                                                                                                             namespace rcs{
                                                                                                                                                                                                                                                                                                                                                                                                 namespace posemath{
                                                                                                                                                                                                                                                                                                                                                                                                     class PmRpy;
                                                                                                                                                                                                                                                                                                                                                                                                      class PmRotationMatrix;
                                                                                                                                                                                                                                                                                                                                                                                                       class PmRotationVector;
                                                                                                                                                                                                                                                                                                                                                                                                      } // end namespace posemath
                                                                                                                                                                                                                                                                                                                                                                                                     } // end namespace rcs

                                                                                                                                                                                                                                                                                                                                                                                                        namespace crcl{
                                                                                                                                                                                                                                                                                                                                                                                                            namespace utils{
                                                                                                                                                                                                                                                                                                                                                                                                                class CRCLPosemathPoseFilter;
                                                                                                                                                                                                                                                                                                                                                                                                               } // end namespace utils
                                                                                                                                                                                                                                                                                                                                                                                                              } // end namespace crcl

                                                                                                                                                                                                                                                                                                                                                                                                                 namespace java{
                                                                                                                                                                                                                                                                                                                                                                                                                     namespace util{
                                                                                                                                                                                                                                                                                                                                                                                                                         namespace concurrent{
                                                                                                                                                                                                                                                                                                                                                                                                                             class ExecutorService;
                                                                                                                                                                                                                                                                                                                                                                                                                            } // end namespace concurrent
                                                                                                                                                                                                                                                                                                                                                                                                                           } // end namespace util

                                                                                                                                                                                                                                                                                                                                                                                                                             namespace nio{
                                                                                                                                                                                                                                                                                                                                                                                                                                 namespace channels{
                                                                                                                                                                                                                                                                                                                                                                                                                                     class Selector;
                                                                                                                                                                                                                                                                                                                                                                                                                                    } // end namespace channels
                                                                                                                                                                                                                                                                                                                                                                                                                                   } // end namespace nio

                                                                                                                                                                                                                                                                                                                                                                                                                                     namespace awt{
                                                                                                                                                                                                                                                                                                                                                                                                                                         class Color;
                                                                                                                                                                                                                                                                                                                                                                                                                                          namespace geom{
                                                                                                                                                                                                                                                                                                                                                                                                                                              class RectangularShape;
                                                                                                                                                                                                                                                                                                                                                                                                                                              class Rectangle2D;
                                                                                                                                                                                                                                                                                                                                                                                                                                              class Rectangle2DDouble;
                                                                                                                                                                                                                                                                                                                                                                                                                                             } // end namespace geom

                                                                                                                                                                                                                                                                                                                                                                                                                                              class Graphics;
                                                                                                                                                                                                                                                                                                                                                                                                                                               class Graphics2D;
                                                                                                                                                                                                                                                                                                                                                                                                                                              } // end namespace awt
                                                                                                                                                                                                                                                                                                                                                                                                                                             } // end namespace java

                                                                                                                                                                                                                                                                                                                                                                                                                                                namespace crcl{
                                                                                                                                                                                                                                                                                                                                                                                                                                                    namespace utils{
                                                                                                                                                                                                                                                                                                                                                                                                                                                        class ProgramPlotterView;
                                                                                                                                                                                                                                                                                                                                                                                                                                                       } // end namespace utils
                                                                                                                                                                                                                                                                                                                                                                                                                                                      } // end namespace crcl

                                                                                                                                                                                                                                                                                                                                                                                                                                                         namespace java{
                                                                                                                                                                                                                                                                                                                                                                                                                                                             namespace awt{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 namespace geom{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     class Dimension2D;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } // end namespace geom

                                                                                                                                                                                                                                                                                                                                                                                                                                                                     class Dimension;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      class Image;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       namespace image{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           class BufferedImage;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } // end namespace image
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         } // end namespace awt
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } // end namespace java

                                                                                                                                                                                                                                                                                                                                                                                                                                                                           namespace javax{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               namespace xml{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   namespace bind{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       class JAXBElement;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } // end namespace bind
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     } // end namespace xml
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } // end namespace javax

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // end namespace crclj
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // end #ifndef crclj_fwd_h
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   #endif
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
