/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeDoubleOp */

#ifndef _Included_NativeDoubleOp
#define _Included_NativeDoubleOp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeDoubleOp
 * Method:    nativeDelete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeDoubleOp_nativeDelete
  (JNIEnv *, jobject);

/*
 * Class:     NativeDoubleOp
 * Method:    applyAsDouble
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_NativeDoubleOp_applyAsDouble
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
