/**************************************************************
 * This C++ file was autogenerated by java4cpp. 
 * It is intended to be modified. It will not be overwritten if it already exists.
 *
 **************************************************************/

#include "test.h"
#include "test_nativerunnable.h"

namespace test {

     void NativeRunnable::initContext(NativeRunnableContext *ctx, bool isref) {
         
    }

    void NativeRunnable::deleteContext() {
        
    }

    void NativeRunnable::runNative() {
         
         return;
    }


}
// End of test

/**************************************************************
 * This C++ file was autogenerated by java4cpp. 
 * It is intended to be modified. It will not be overwritten if it already exists.
 *
 **************************************************************/
