/**************************************************************
 * This header file was autogenerated by java4cpp. 
 * It is intended to be modified. It will not be overwritten if it already exists.
 *
 **************************************************************/
#ifndef test_NativeDoubleOp_H
#define test_NativeDoubleOp_H

namespace test {

    class NativeDoubleOpContext {
        // add any data to store per object
    };
}

#endif
// end of #ifndef test_NativeDoubleOp_H
