/**************************************************************
 * This C++ file was autogenerated by java4cpp. 
 * It is intended to be modified. It will not be overwritten if it already exists.
 *
 **************************************************************/

#include "test.h"
#include "test_nativedoubleop.h"

namespace test {

     void NativeDoubleOp::initContext(NativeDoubleOpContext *ctx, bool isref) {
         
    }

    void NativeDoubleOp::deleteContext() {
        
    }

    jdouble NativeDoubleOp::applyAsDoubleNative(jdouble double_0) {
        return double_0 +1.0;
    }

}
// End of test

/**************************************************************
 * This C++ file was autogenerated by java4cpp. 
 * It is intended to be modified. It will not be overwritten if it already exists.
 *
 **************************************************************/
