/**************************************************************
 * This header file was autogenerated by java4cpp. 
 * It is intended to be modified. It will not be overwritten if it already exists.
 *
 **************************************************************/
#ifndef test_NativeRunnable_H
#define test_NativeRunnable_H

namespace test {

    class NativeRunnableContext {
    public:
        // add any data to store per object
        int run_count;
    };
}

#endif
// end of #ifndef test_NativeRunnable_H
